# Numpy

In [1]:
import numpy as np

In [2]:
X = np.array([1,2,3])
print(X)

[1 2 3]


In [13]:
type(X)

numpy.ndarray

In [5]:
l = [4 , 5 , 10]
X = np.asarray(l)
type(X)

numpy.ndarray

In [8]:
X.dtype

dtype('int64')

In [9]:
X = np.asarray(l , 'float64')

In [10]:
X.dtype

dtype('float64')

In [15]:
X = np.array([[1,2,3], [4,5,6]])

In [18]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
X[0 , :]

array([1, 2, 3])

In [22]:
X[:,0]

array([1, 4])

# Builtin Types of Matrices

In [26]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.random.randint(low=4,high=10,size=(3,4))

array([[4, 6, 4, 7],
       [6, 7, 8, 5],
       [5, 6, 7, 5]])

In [36]:
Y = X.reshape(-1,1)
Y

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [39]:
np.arange(6).reshape((3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

# VECTORS

In [43]:
A = np.arange(5)
B = np.arange(5,10)

In [46]:
print(A+B, A-B, A * B , A / B, sep="\n")

[ 5  7  9 11 13]
[-5 -5 -5 -5 -5]
[ 0  6 14 24 36]
[0.         0.16666667 0.28571429 0.375      0.44444444]


In [48]:
np.floor(A/B)

array([0., 0., 0., 0., 0.])

In [54]:
np.floor (np.random.random((2,3)) * 10 )

array([[0., 5., 9.],
       [3., 9., 7.]])

In [56]:
np.inner(A,B)

80

In [58]:
np.dot(A,B)

80

In [60]:
np.outer(A,B)

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  7,  8,  9],
       [10, 12, 14, 16, 18],
       [15, 18, 21, 24, 27],
       [20, 24, 28, 32, 36]])

In [63]:
X.sum()

21

In [65]:
X.sum(axis = 0)

array([5, 7, 9])

In [66]:
X.sum(axis = 1)

array([ 6, 15])